DATABASE QUERIES:
---USER---
CREATE TABLE USER(
  USER_ID             INT NOT NULL,
  USER_NAME           VARCHAR(30) NOT NULL,
  USER_EMAIL          VARCHAR(30) NOT NULL,
  USER_NUMBER         INT NOT NULL,
  USER_DOB            VARCHAR(30) NOT NULL,
  USER_ADDRESS        VARCHAR(30) UNIQUE NOT NULL
  );


---PRODUCT---
CREATE TABLE PRODUCT(
  PRODUCT_ID          INT NOT NULL,
  PRODUCT_NAME        VARCHAR(30) NOT NULL,
  PRODUCT_ADDRESS     VARCHAR(30) NOT NULL,
  PRODUCT_PRICE       INT NOT NULL,
  PRODUCT_DESCRIPTION VARCHAR(30) NOT NULL,
  );


---LOCATION---
CREATE TABLE LOCATION(
  LOCATION_INIT       VARCHAR(30) NOT NULL,
  LOCATION_INIT_ETA   DATE NOT NULL,
  LOCATION_FINAL      VARCHAR(30) NOT NULL,
  LOCATION_FINAL_ETA  DATE NOT NULL,
  LOCATION_CURR       VARCHAR(30) NOT NULL,
  LOCATION_CURR_ETA   DATE NOT NULL,
  LOCATION_LAST       VARCAHR(30),
  LOCATION _NEXT      VARCHAR(30),
  FOREIGN KEY (LOCATION_INIT) REFERENCES PRODUCT(PRODUCT_ADDRESS).
  FOREIGN KEY (LOCATION_FINAL) REFERENCES USER(USER_ADDRESS)
  );


---SERVICE---
CREATE TABLE SERVICE(
  SERVICE_NAME        VARCHAR(30) UNIQUE NOT NULL,
  SERVICE_ID          VARCHAR(30) UNIQUE NOT NULL,
  SERVICE_NUMBER      VARCHAR(30) NOT NULL,
  SERVICE_EMAIL       VARCHAR(30) NOT NULL,
  SERVICE_TYPE        VARCHAR(30) NOT NULL,
  PRIMARY KEY(SERVICE_NUMBER)
  );


---PAYMENT---
CREATE TABLE PAYMENT(
  PAYMENT_NUMBER      VARCHAR(30) NOT NULL,
  PAYMENT_METHOD      VARCHAR(30) NOT NULL,
  PAYMENT_STATUS      VARCHAR(30) NOT NULL,
  FOREIGN KEY (PAYMENT_NUMBER) REFERENCES SERVICE(SERVICE_NUMBER)
  );
  
  
---SERVICEREVIEW---
CREATE TABLE SERVICE_REVIEW(
  SERVICE_ID VARCHAR(30),
  SERVICE_NUMBER VARCHAR(30),
  SERVICE_NAME VARCHAR(30),
  GRADE VARCHAR(30),
  SCORE INT
  );
  
  
---PRODUCT REVIEW---
CREATE TABLE PRODUCT_REVIEW(
  PRODUCT_ID VARCHAR(30),
  PRODUCT_NAME VARCHAR(30),
  PRODUCT_SELLER VARCHAR(30),
  PRODUCT_REVIEW VARCHAR(30),
  PRODUCT_SCORE INT
  );
  
