---USER---
CREATE TABLE USER(
  USER_ID             INT,
  USER_NAME           VARCHAR(30),
  USER_EMAIL          VARCHAR(30),
  USER_NUMBER         INT,
  USER_DOB            VARCHAR(30),
  USER_ADDRESS        VARCHAR(30)
  );

---PRODUCT---
CREATE TABLE PRODUCT(
  PRODUCT_ID          INT,
  PRODUCT_NAME        VARCHAR(30),
  PRODUCT_ADDRESS     VARCHAR(30),
  PRODUCT_PRICE       INT,
  PRODUCT_DESCRIPTION VARCHAR(30),
  PRODUCT_DESTINATION VARCHAR(30),
  );
  
---LOCATION---
CREATE TABLE LOCATION(
  LOCATION_INIT       VARCHAR(30),
  LOCATION_INIT_ETA   DATE,
  LOCATION_FINAL      VARCHAR(30),
  LOCATION_FINAL_ETA  DATE,
  LOCATION_CURR       VARCHAR(30),
  LOCATION_CURR_ETA   DATE
  );
  
---SERVICE---
CREATE TABLE SERVICE(
  SERVICE_NAME        VARCHAR(30),
  SERVICE_ID          VARCHAR(30),
  SERVICE_NUMBER      VARCHAR(30),
  SERVICE_EMAIL       VARCHAR(30),
  SERVICE_TYPE        VARCHAR(30)
  );
